### ISSUE TITLE
[fluxible-addons-react] react 16 task list

### ISSUE THREAD

**Issue by redonkulus** [yahoo/fluxible#654]
@pablopalacios 

We want to support the latest and great features of React, while deprecating older features. This will facilitate a new 1.x major version release in fluxible-addons-react.

### Tasks

- [x] Use ES2015 features - #646
- [x] Remove polyfill and drop old react support
- [x] Remove decorator support - #653
- [x] Remove mixins #653
- [x] Update to use the newer context API (solves #584 )
- [x] Update example app to use new APIs
- [x] Update generator to use new APIs - https://github.com/yahoo/fluxible/pull/690
- [x] Update fluxible website docs / examples for new APIs
- [x] Improve packaging for fluxible-router to make it tree-shakeable and decrease bundle size
- [x] Simplify provideContext since I've found that we don't even need to pass a list of plugins to inject their component context.
- [x] Publish fluxible-router and fluxible-addons-react without beta
- [x] Update examples to remove prelease tag dependencies
- [x] Update CHANGELOG.md of fluxible-router and fluxible-addons-react to add links to MIGRATION guides
- [x] Update fluxilble.io site to use new packages and APIs

### Resolves

- #584
- #636

**Comment by pablopalacios** [comment]
@redonkulus regarding the polyfills: given that we didn't add any, could we mark this as done? (react deprecation was done in #653 )

**Comment by redonkulus** [comment]
Sure, that's fine.

**Comment by pablopalacios** [comment]
@redonkulus so I'm done with my changes on the context step. After context PR is merged, it would be cool to have a beta release so I can start tackling the example app and the generator.

**Comment by redonkulus** [comment]
@pablopalacios fluxible-addons-react@1.0.0-beta.0 released under the `next` tag on npm.

**Comment by pablopalacios** [comment]
@redonkulus could we bump `fluxible-router` on npm as well? It is currently not compatible with addons beta version.

**Comment by redonkulus** [comment]
@pablolmiranda `fluxible-router@2.0.0-beta.7.0` released as well.

**Comment by pablopalacios** [comment]
By the way, the `Update to use the newer context API`  task is already done (#663 ) as well as the `Update fluxible website docs` (#668 ). Now I'm working on creating the new examples.

**Comment by redonkulus** [comment]
Ok cool, I updated the check list

**Comment by pablopalacios** [comment]
@redonkulus could we have new beta releases for `fluxible-addons-react` and `fluxible-router`?

**Comment by redonkulus** [comment]
@pablopalacios both have been published

**Comment by pablopalacios** [comment]
2 more items before removing the beta tag:
- Improve packaging for fluxible-router to make it tree-shakeable and decrease bundle size
- Simplify `provideContext` since I've found that we don't even need to pass a list of plugins to inject their component context.

**Comment by redonkulus** [comment]
Ok I've added those to the list above. What changes for fluxible-router are you thinking?

**Comment by pablopalacios** [comment]
Before removing the beta tag I would only improve packaging as did here: https://github.com/yahoo/fluxible/pull/683/commits

But later I would like to simplify tests and remove the dependency on addons-react components refs. They prevent us to convert addons-react components to functional components, which would allow us to decrease even further the package size. 

However, since removing refs from addons-react would be a breaking change, maybe it would be better to do it right now as well. What do you think?

**Comment by redonkulus** [comment]
The best time to do it is now, before we remove the beta tag. Otherwise l, we would need to do another breaking change release.

**Comment by pablopalacios** [comment]
Right. And what should be done on the `Update example app to use new APIs` task? What is the example app?

**Comment by redonkulus** [comment]
I think I meant that to be plural, which you have done for the most part. Would be convert the remaining examples too if you have time. Otherwise, we could just remove them. It was nice showcasing different usecases to users.

**Comment by pablopalacios** [comment]
@redonkulus with #710 I'm done with all the changes I would like to do before removing the beta tag.

**Comment by redonkulus** [comment]
Ok sounds good. Will review today.

**Comment by redonkulus** [comment]
@pablopalacios one important task I've added to the bottom of the list is updating the fluxible.io site to use the new APIs, is that something you think you could help out on?

I know you did some work [here](https://github.com/yahoo/fluxible/commit/ab521a47390486e4a6ca1ecb2e71ad591651792d) but wasn't sure if there was any last cleanup to do.

**Comment by pablopalacios** [comment]
I'll check it one more time. In theory, it should be working.

**Comment by pablopalacios** [comment]
Done: https://github.com/yahoo/fluxible/pull/715

**Comment by pablopalacios** [comment]
@redonkulus what is really missing on this one? Anything that I could do?

**Comment by redonkulus** [comment]
So the 3 bullets that are open are what is left. If you think we are ready, we can merge the development branch into master and release all the packages without the beta flags. Then we will need to finish up the remaining tasks (updating the site to use latest and make sure migration guides are setup properly).

Last master has been rebased into the dev branch right?

**Comment by pablopalacios** [comment]
Hmmm... I don't think so. But I thought a little bit more. It might be good to make a release of the old packages with deprecation warnings to make it easier to migrate to the newer versions. After that I think we can merge.

**Comment by redonkulus** [comment]
I wouldn't do that as that will create a lot of noise for "stable" versions. Especially internally when we will probably never migrate to the new versions because resources are constrained and it would be a lot of work to refactor.

Can you do one last master rebase into the dev branch before we merge?

**Comment by redonkulus** [comment]
@pablopalacios since all the packages have been released now, I'm going to close this out. Thanks again for all your hard work and making fluxible better for everyone!
